// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK0DdHoamADRNIrLNxx7XEjnRjf6JhlDw',
    appId: '1:645373992293:web:01efc262959a655b5fd58c',
    messagingSenderId: '645373992293',
    projectId: 'gezenti-app',
    authDomain: 'gezenti-app.firebaseapp.com',
    storageBucket: 'gezenti-app.firebasestorage.app',
    measurementId: 'G-DZYSF6CBS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZaewhFsl6weBtCueh_-afHxsWwvOEDnA',
    appId: '1:645373992293:android:ed88cb67fea4ee755fd58c',
    messagingSenderId: '645373992293',
    projectId: 'gezenti-app',
    storageBucket: 'gezenti-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOLvSD4zUUBxnSewRT44Cs53L8PHnoLFs',
    appId: '1:645373992293:ios:1aa206d8df1212fb5fd58c',
    messagingSenderId: '645373992293',
    projectId: 'gezenti-app',
    storageBucket: 'gezenti-app.firebasestorage.app',
    iosBundleId: 'com.example.gezentiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOLvSD4zUUBxnSewRT44Cs53L8PHnoLFs',
    appId: '1:645373992293:ios:1aa206d8df1212fb5fd58c',
    messagingSenderId: '645373992293',
    projectId: 'gezenti-app',
    storageBucket: 'gezenti-app.firebasestorage.app',
    iosBundleId: 'com.example.gezentiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBK0DdHoamADRNIrLNxx7XEjnRjf6JhlDw',
    appId: '1:645373992293:web:5ffe647ef285515b5fd58c',
    messagingSenderId: '645373992293',
    projectId: 'gezenti-app',
    authDomain: 'gezenti-app.firebaseapp.com',
    storageBucket: 'gezenti-app.firebasestorage.app',
    measurementId: 'G-M3LLEJE91D',
  );
}
